javascript-objects - Jeremy Nguyen
jeremyhnguyen/c-0823-code-solutions pull request #3
Opened 2023-08-28 23:43 UTC by jeremyhnguyen

<img width="551" alt="Screenshot 2023-08-28 at 4 33 58 PM" src="https://github.com/jeremyhnguyen/c-0823-code-solutions/assets/136545701/f2894871-2dd5-4d96-90fd-6005e2fc3e01">

2023-08-28 23:48 UTC, shawnkost requested changes
One change, and one comment here!

2023-08-28 23:48 UTC, shawnkost commented on javascript-objects/main.js
> +vehicle['isConvertible'] = 'no';
The value for this should be a boolean rather than a string

2023-08-28 23:48 UTC, shawnkost commented on javascript-objects/main.js
> +console.log('value of pet: ' + pet);
Do you see how in your console, you're getting `value of pet: [object, Object]`? This is exactly why we don't want to do console logs with the `+` operator, and we want to use a `,` to separate them instead. I will touch on this behavior in our Q&A.

2023-08-28 23:55 UTC, jeremyhnguyen commented
Fixed the boolean as well as the console log error, I forgot to switch to a comma for the last one after I went back through it.

<img width="552" alt="Screenshot 2023-08-28 at 4 50 11 PM" src="https://github.com/jeremyhnguyen/c-0823-code-solutions/assets/136545701/0e3bda32-b9e4-4363-b241-51e0c2e4821a">

2023-08-29 04:29 UTC, shawnkost approved these changes
👍🏻

2023-08-29 17:45 UTC, merged